### ISSUE TITLE
Typo dans le script

### ISSUE THREAD

**Issue by cyxae** [Ced-C/Bepolar#1]
https://github.com/Ced-C/Bepolar/blob/8739904e9bef72af04c1ce75bfcaac77210a09fa/scripts/quick_install.sh#L14

Allô ! Je pense qu’à cet endroit on cherche plutôt *xkb* que *xbk* sinon ça donne une erreur… et la variable $path est-elle bien définie ?

**Comment by Oni-Shadow** [comment]
Merci, effectivement je corrige cela ! 
Comment es-tu tombé sur ma petite dispo ?

**Comment by Ced-C** [comment]
Merci, effectivement je corrige cela !
Comment es-tu tombé sur ma petite dispo ?

**Comment by Ced-C** [comment]
Ça devrait être bon avec le _commit_ #6fb6c3f 
On voit bien que je ne suis pas dev ^^ je n’ai pas les codes de github. Je ne sais même pas écrire Script dans mes _commits_ d’ailleurs !

**Comment by cyxae** [comment]
En trainant sur les Discord du bépo et de ErgoL je suis tombé dessus !
