### ISSUE TITLE
bepolar.keylayout non reconnu sur un mac

### ISSUE THREAD

**Issue by soli** [Ced-C/Bepolar#3]
Bonjour,

je voulais passer de bépo que j'utilise depuis des années à bépolar, mais je rencontre un souci.
Contrairement aux vieux drivers bépo, ou au dernier driver ergo-L (1.0.0), mon Mac (en Ventura, donc MacOS 13.6.7 si ça a une importance) refuse de me proposer Bépolar dans les "Input Sources".

Je n'arrive à rien trouver dans les logs et n'ai aucune idée de comment débugguer ça, mais… je note que dans ergol.keylayout j'ai des trucs du genre :

`<key code="18"  action="ae01_1" />` quand dans bepolar.keylayout j'ai `<key code="18"  action="1" />`

de même j'ai ça`<key code="19"  action="«" />` pour bepolar plutôt que `<key code="19"  action="ae02_«" />` dans ergol…

J'ai essayé d'installer `kalamine` et de le faire tourner sur Bepolar.yml mais j'ai eu des messages d'erreur… du coup… des idées ?

**Comment by Ced-C** [comment]
Bonjour, oui il y a eu un petit soucis avec ça dans la semaine à cause d’une étourderie de ma part. On a trouvé la solution (qui était sur la branche dev) et je viens de merger.
Donc sauf erreur de ma part, cela devrait être tout bon maintenant !

**Comment by soli** [comment]
Super, ça marche, merci !
